## Basic Tensor Operations using Tensorflow V2

In [3]:
import tensorflow as tf
#import numpy as np

In [2]:
# Define tensor constants.
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [7]:
# Various tensor operations

add = tf.add(a,b)
mul = tf.multiply(b,c)
sub = tf.subtract(c,a)
div = tf.divide(a,b)

print("addtion = ", add.numpy())
print("multipy = ", mul.numpy())
print("subtract = ", sub.numpy())
print("divide = ", div.numpy())

addtion =  5
multipy =  15
subtract =  3
divide =  0.6666666666666666


In [11]:
# Some more operations

'''https://www.tensorflow.org/api_docs/python/tf/math/reduce_std'''

mean = tf.reduce_mean([a,b,c])
prod = tf.reduce_prod([a,b,c])

print("mean = ", mean.numpy())
print("prod = ", std.numpy())

mean =  3
prod =  30


In [12]:
# Matrix multiplications.

M1 = tf.constant([[2,6,8], [5,8,3], [2,9,5]])

M2 = tf.constant([[3,9,1], [4,8,2], [5,1,9]])

product = tf.matmul(M1, M2)

In [13]:
# Display Tensor
product

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 70,  74,  86],
       [ 62, 112,  48],
       [ 67,  95,  65]], dtype=int32)>

In [14]:
# using numpy
product.numpy()

array([[ 70,  74,  86],
       [ 62, 112,  48],
       [ 67,  95,  65]], dtype=int32)

In [18]:
# creating Tnesor

hello = tf.constant("Hello World")
print(hello)


tf.Tensor(b'Hello World', shape=(), dtype=string)
b'Hello World'


In [19]:
# to access the tensor value, call numpy()
print(hello.numpy())

b'Hello World'
